### ISSUE TITLE
[must]仕様書に適していない関数を整理する

### ISSUE THREAD

**Issue by iamtatsuki05** [al22-1B-01/meal_shield#28]
- https://github.com/al22-1B-01/meal_shield/blob/develop/frontend/src/meal_shield/detail.py#L4

**Comment by xEuphemia** [comment]
ランキング処理部は2024/06/28時点で一通り確認しましたが、仕様書に適していない関数や変数はありませんでした。

**Comment by xEuphemia** [comment]
https://github.com/al22-1B-01/meal_shield/blob/76d2a3d8341ee2ffef735598139bcc3f51d212a5/frontend/src/meal_shield/detail.py#L4

**Comment by xEuphemia** [comment]
https://github.com/al22-1B-01/meal_shield/blob/76d2a3d8341ee2ffef735598139bcc3f51d212a5/frontend/src/meal_shield/display_recipi.py#L6C1-L10C11

**Comment by xEuphemia** [comment]
https://github.com/al22-1B-01/meal_shield/blob/76d2a3d8341ee2ffef735598139bcc3f51d212a5/frontend/src/meal_shield/search.py#L10C1-L10C62
→fetch_recipe_detail？

**Comment by xEuphemia** [comment]
frontend：
display_recipe_detail_entrypoint
input_allergy_recipe_info
get_recipe_summary
make_recipi_summary
fetch_recipe_detail
以上の関数が無い？

**Comment by xEuphemia** [comment]
backend側は問題なし
