### ISSUE TITLE
[want]スクレイピングの時のパフォーマンスを改善する

### ISSUE THREAD

**Issue by iamtatsuki05** [al22-1B-01/meal_shield#38]
## 背景
- スクレイピングしている処理時間が異常にかかっていそう

## ToDo
- [ ] 以下設定でのパフォーマンスの調査
  - [ ] 順次処理
    - [ ] レシピ数＝1のときの秒数数：...
    - [ ] レシピ数＝100のときの秒数数：...
  - [ ] #44
    - [ ] 並列数：...
    - [ ] レシピ数＝1のときの秒数数：...
    - [ ] レシピ数＝100のときの秒数数：...
  - [ ] 並行処理
     - [ ] 並列数：...
     - [ ] レシピ数＝1のときの秒数数：...
    - [ ] レシピ数＝100のときの秒数数：...
  - [ ] 非同期処理
    - [ ] 並列数：...
    - [ ] レシピ数＝1のときの秒数数：...
    - [ ] レシピ数＝100のときの秒数数：...
    - https://note.com/kuwaharu/n/n500722e821e3
    - https://docs.python.org/ja/3/library/multiprocessing.html#multiprocessing.pool.Pool.apply_async:~:text=apply_async(func,%E3%81%99%E3%82%8B%E3%81%8B%E3%82%89%E3%81%A7%E3%81%99%E3%80%82
- [ ] ↑で最適な実装に変更し、必要に応じて影響コードを変更する
- [ ] ループ処理しているところにtqdmの追加＋descオプションで処理内容を明記
   - https://qiita.com/MAsa_min/items/27052f752abe68939855

**Comment by okiijin** [comment]
並列処理
 並列数：8
 レシピ数＝1のときの秒数数：00:00
 レシピ数＝100のときの秒数数：00:35~01:14
処理が重いからか同じ条件の検索でもスムーズに処理が終わる場合と途中で処理が止まる場合がある

**Comment by okiijin** [comment]
非同期処理
 並列数：
 レシピ数＝1のときの秒数数：00:00
 レシピ数＝100のときの秒数数：00:23~01:20
一度関数scraping_recipe_urlで処理が止まったが、発生確率は低く、基本20程度で処理が終わる。処理が止まるのはパソコンや通信環境の問題かもしれない。並列処理より非同期処理が適していそう。
